name: Ruby

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.7', '3.0', '3.1', '3.2' ]
    name: Ruby ${{ matrix.ruby }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: |
        rake build
        gem install ./pkg/fluent-plugin-utmpx*.gem
        TESTOPTS="--verbose" bundle exec rake
