name: Ruby

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.5', '2.6', '2.7', '3.0' ]
        fluentd: ['1.11.5', '1.12.2']
    name: Ruby ${{ matrix.ruby }} unit testing on ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Run the default task
      run: |
        gem install fluentd -v ${{ matrix.fluentd }}
        gem install rake -v 12.0
        gem install webrick
        rake build
        gem install ./pkg/fluent-plugin-utmpx*.gem
        TESTOPTS="--verbose" bundle exec rake
